<a href="https://colab.research.google.com/github/chrisdionisius/MachineLearning2022/blob/main/Jobsheet09_2_bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bagging dengan RandomForest

Pada kasus ini kita akan menggunakan salah satu metode bagging yaitu RandomForest untuk mengklasifikasikan jenis tumor. Dalam latihan ini Anda akan melakukan training dengan data [Wisconsin Breast Cancer Dataset](https://www.kaggle.com/uciml/breast-cancer-wisconsin-data) dari UCI machine learning repository. Latihan ini akan melakukan prediksi memprediksi apakah tumor ganas atau jinak.

Kita akan membandingkan performa dari algoritma Decision Tree dan RandomForest pada kasus ini.

In [113]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Import Library

In [114]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # import DT
from sklearn.ensemble import RandomForestClassifier # import RandomForest
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

### Persiapan Data

In [115]:
# Load data
df = pd.read_csv('/content/drive/MyDrive/dataset/wbc.csv')

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [116]:
# Cek kolom null
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [117]:
# Seleksi fitur

# Slice dataframe mulai dari kolom 'radius_mean' sampai 'fractal_dimension_worst'
X = df.iloc[:,3:-1]
y = df['diagnosis']
y = y.map({'M':1, 'B':0}) # Encode label

# Cek jumlah fitur dan instance
X.shape

(569, 29)

### Split data training dan testing

In [118]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

### Traning Decision Tree

In [119]:
# Secara default, DecisionTreeClassifier dari scikit-learn akan menggunakan nilai "Gini" untuk kriteria
# Terdapat beberapa "hyperparamater" yang dapat digunakan. Silahka baca dokumentasi
# Pada kasus ini kita akan menggunakan parameter default
dt = DecisionTreeClassifier()

# Sesuaikan dt ke set training
dt.fit(X_train, y_train)

# Memprediksi label set test
y_pred_dt = dt.predict(X_test)

#  menghitung set accuracy
acc_dt = accuracy_score(y_test, y_pred_dt)
print("Test set accuracy: {:.2f}".format(acc_dt))
print(f"Test set accuracy: {acc_dt}")

Test set accuracy: 0.93
Test set accuracy: 0.9298245614035088

### Training RandomForest

In [120]:
# Pada kasus kali ini kita akan menggunakan seluruh parameter default dari RandomForest
# Untuk detail parameter (hyperparameter) silahkan cek dokumentasi

rf = RandomForestClassifier(n_estimators=10, random_state=1)

# Sesuaikan dt ke set training
rf.fit(X_train, y_train)

# Memprediksi label set test
y_pred_rf = rf.predict(X_test)

#  menghitung set accuracy
acc_rf = accuracy_score(y_test, y_pred_rf)
print("Test set accuracy: {:.2f}".format(acc_rf))
print(f"Test set accuracy: {acc_rf}")

Test set accuracy: 0.96
Test set accuracy: 0.956140350877193

### Tugas

Pada folder data, terdapat dataset jamur yang kita gunakan pada materi Decision Tree. Berdasarkan dataset yang sama, bandingkan peforma antara algoritma DT dan RandomForest. Gunakan tunning hyperparameter untuk mendapatkan parameter dan akurasi yang terbaik.

# Decision Tree

In [121]:
# baca data
data = pd.read_csv('/content/drive/MyDrive/dataset/mushrooms.csv')
data.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [122]:
# DESCRIBING
data.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

In [123]:
data['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [124]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for column in data.columns:
    data[column] = labelencoder.fit_transform(data[column])

data.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1

In [125]:
data = data.drop(["veil-type"],axis=1)

In [126]:
X = data[['cap-color', 'odor']]
y = data['class']

In [127]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [128]:
from sklearn.tree import DecisionTreeClassifier

# Instantiate DecisionTreeClassifier 'dt' dengan kedalaman maksimum 6
dt = DecisionTreeClassifier(max_depth=8, random_state=1)

# Sesuaikan dt ke set training
dt.fit(X_train, y_train)

# Pmemprediksi label set test
y_pred = dt.predict(X_test)
print(y_pred[0:5])

[0 1 1 1 0]

In [129]:
from sklearn.metrics import accuracy_score

# Memprediksi test set labels
y_pred = dt.predict(X_test)

#  menghitung set accuracy
acc = accuracy_score(y_test, y_pred)
print("Test set accuracy: {:.2f}".format(acc))

Test set accuracy: 0.98

In [130]:
from sklearn.tree import DecisionTreeClassifier

# Instantiate dt_entropy, set 'entropy' sebagai kriteria informasi
dt_entropy = DecisionTreeClassifier(max_depth=8, criterion='entropy', random_state=1)

# Fit dt_entropy kedalam training set
dt_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=8, random_state=1)

In [131]:
dt_gini = DecisionTreeClassifier(max_depth=6, criterion='gini', random_state=1)
dt_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6, random_state=1)

In [132]:
from sklearn.metrics import accuracy_score

# menggunakan dt_entropy untuk memprediksi test set labels
y_pred = dt_entropy.predict(X_test)
y_pred_gini = dt_gini.predict(X_test)

# mengevaluasi accuracy_entropy
accuracy_entropy = accuracy_score(y_test, y_pred)
accuracy_gini = accuracy_score(y_test, y_pred_gini)

# Print accuracy_entropy
print("Accuracy achieved by using entropy: ", accuracy_entropy)

# Print accuracy_gini
print("Accuracy achieved by using gini: ", accuracy_gini)

Accuracy achieved by using entropy:  0.984
Accuracy achieved by using gini:  0.9803076923076923

In [133]:
decision_tree_cls = DecisionTreeClassifier(random_state=13)  # Create instance for model
decision_tree_cls.fit(X_train, y_train)  # Fit data with model

print("Train Score for Decision Tree: ", decision_tree_cls.score(X_train, y_train))  # Print Train Score
print("Test Score for Decision Tree: ", decision_tree_cls.score(X_test, y_test))  # Print Test Score

Train Score for Decision Tree:  0.9892291121711032
Test Score for Decision Tree:  0.984

In [134]:
decision_tree_cls.get_params()  # Print hyperparameters and their values for the model

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 13,
 'splitter': 'best'}

In [135]:
from sklearn.model_selection import GridSearchCV
# Specifying hyperparameters' range for the model:
parameters_DT = {"max_depth" : np.arange(3, 20)}

# Create a Grid Search Cross Validation instance ("n_jobs=-1" means use all cores of the processor):
grid_search_DT = GridSearchCV(decision_tree_cls, parameters_DT, cv=6, n_jobs=-1, return_train_score=True)

# Fit Grid Search model with data:
grid_search_DT.fit(X_train, y_train)

# Show results for all combinations:
pd.DataFrame(grid_search_DT.cv_results_)[["params", "mean_fit_time", "mean_train_score", "mean_test_score"]]

               params  mean_fit_time  mean_train_score  mean_test_score
0    {'max_depth': 3}       0.007203          0.981843         0.981844
1    {'max_depth': 4}       0.007588          0.983382         0.983382
2    {'max_depth': 5}       0.007325          0.983382         0.983382
3    {'max_depth': 6}       0.006828          0.986459         0.986460
4    {'max_depth': 7}       0.006472          0.989229         0.989229
5    {'max_depth': 8}       0.006096          0.989229         0.989229
6    {'max_depth': 9}       0.006664          0.989229         0.989229
7   {'max_depth': 10}       0.006491          0.989229         0.989229
8   {'max_depth': 11}       0.006664          0.989229         0.989229
9   {'max_depth': 12}       0.007417          0.989229         0.989229
10  {'max_depth': 13}       0.009538          0.989229         0.989229
11  {'max_depth': 14}       0.005089          0.989229         0.989229
12  {'max_depth': 15}       0.005285          0.989229         0.989229
13  {'max_depth': 16}       0.005259          0.989229         0.989229
14  {'max_depth': 17}       0.005132          0.989229         0.989229
15  {'max_depth': 18}       0.006517          0.989229         0.989229
16  {'max_depth': 19}       0.006831          0.989229         0.989229

In [136]:
grid_search_DT.best_params_  # Print best hyperparameters for the model

{'max_depth': 7}

In [146]:
# Decision Tree Classifier:
decision_tree_cls_tuned = DecisionTreeClassifier(max_depth=14, random_state=13)
decision_tree_cls_tuned.fit(X_train, y_train)

# Find test accuracy for all models:
print("Test Score for Decision Tree: ", decision_tree_cls_tuned.score(X_test, y_test))

Test Score for Decision Tree:  1.0

# Random Forest

In [147]:
# baca data
data_2 = pd.read_csv('/content/drive/MyDrive/dataset/mushrooms.csv')
data_2.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [148]:
# Cek kolom null
data_2.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [149]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for column in data_2.columns:
    data_2[column] = labelencoder.fit_transform(data_2[column])

data_2.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1

In [150]:
# Seleksi fitur

# Slice dataframe mulai dari kolom 'cap-shape' sampai 'habitat'
X = data_2.iloc[:,3:-1]
y = data_2['class']
# y = y.map({'p':1, 'e':0}) # Encode label

# Cek jumlah fitur dan instance
X.shape

(8124, 19)

In [151]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [153]:
# Pada kasus kali ini kita akan menggunakan seluruh parameter default dari RandomForest
# Untuk detail parameter (hyperparameter) silahkan cek dokumentasi

rf = RandomForestClassifier(n_estimators=10, random_state=1)

# Sesuaikan dt ke set training
rf.fit(X_train, y_train)

# Memprediksi label set test
y_pred_rf = rf.predict(X_test)

#  menghitung set accuracy
acc_rf = accuracy_score(y_test, y_pred_rf)
print("Test set accuracy: {:.2f}".format(acc_rf))
print(f"Test set accuracy: {acc_rf}")

Test set accuracy: 1.00
Test set accuracy: 1.0

In [154]:
random_forest_cls = RandomForestClassifier(random_state=13)  # Create instance for model
random_forest_cls.fit(X_train, y_train)  # Fit data with model

print("Train Score for Random Forest: ", random_forest_cls.score(X_train, y_train))  # Print Train Score
print("Test Score for Random Forest: ", random_forest_cls.score(X_test, y_test))  # Print Test Score

Train Score for Random Forest:  1.0
Test Score for Random Forest:  1.0

In [155]:
random_forest_cls.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 13,
 'verbose': 0,
 'warm_start': False}

In [156]:
# Specifying hyperparameters' range for the model:
parameters_RF = {"max_depth" : np.arange(5, 15),
                 "n_estimators" : [100, 200, 300]}

# Create a Grid Search Cross Validation instance ("n_jobs=-1" means use all cores of the processor):
grid_search_RF = GridSearchCV(random_forest_cls, parameters_RF, cv=6, n_jobs=-1, return_train_score=True)

# Fit Grid Search model with data:
grid_search_RF.fit(X_train, y_train)

# Show results for all combinations:
pd.DataFrame(grid_search_RF.cv_results_)[["params", "mean_fit_time", "mean_train_score", "mean_test_score"]]

,params,mean_fit_time,mean_train_score,mean_test_score
0,"{'max_depth': 5, 'n_estimators': 100}",0.425787,0.991168,0.991075
1,"{'max_depth': 5, 'n_estimators': 200}",0.832986,0.991568,0.991383
2,"{'max_depth': 5, 'n_estimators': 300}",1.643853,0.991414,0.991229
3,"{'max_depth': 6, 'n_estimators': 100}",0.445573,0.995538,0.994768
4,"{'max_depth': 6, 'n_estimators': 200}",0.847736,0.996153,0.995845
5,"{'max_depth': 6, 'n_estimators': 300}",1.266026,0.995846,0.995691
6,"{'max_depth': 7, 'n_estimators': 100}",0.443925,0.998431,0.998000
7,"{'max_depth': 7, 'n_estimators': 200}",1.407536,0.999692,0.998923
8,"{'max_depth': 7, 'n_estimators': 300}",1.271551,0.998554,0.997846
9,"{'max_depth': 8, 'n_estimators': 100}",0.443760,1.000000,1.000000
10,"{'max_depth': 8, 'n_estimators': 200}",0.872903,1.000000,1.000000
11,"{'max_depth': 8, 'n_estimators': 300}",1.283022,1.000000,1.000000
12,"{'max_depth': 9, 'n_estimators': 100}",0.464899,1.000000,1.000000
13,"{'max_depth': 9, 'n_estimators': 200}",0.852314,1.000000,1.000000
14,"{'max_depth': 9, 'n_estimators': 300}",1.254874,1.000000,1.000000
15,"{'max_depth': 10, 'n_estimators': 100}",0.435983,1.000000,1.000000
16,"{'max_depth': 10, 'n_estimators': 200}",0.854885,1.000000,1.000000
17,"{'max_depth': 10, 'n_estimators': 300}",1.305839,1.000000,1.000000
18,"{'max_depth': 11, 'n_estimators': 100}",0.431243,1.000000,1.000000
19,"{'max_depth': 11, 'n_estimators': 200}",0.864044,1.000000,1.000000
20,"{'max_depth': 11, 'n_estimators': 300}",1.286843,1.000000,1.000000
21,"{'max_depth': 12, 'n_estimators': 100}",0.456312,1.000000,1.000000
22,"{'max_depth': 12, 'n_estimators': 200}",0.893567,1.000000,1.000000
23,"{'max_depth': 12, 'n_estimators': 300}",1.876577,1.000000,1.000000
24,"{'max_depth': 13, 'n_estimators': 100}",0.437237,1.000000,1.000000
25,"{'max_depth': 13, 'n_estimators': 200}",0.863040,1.000000,1.000000
26,"{'max_depth': 13, 'n_estimators': 300}",1.277269,1.000000,1.000000
27,"{'max_depth': 14, 'n_estimators': 100}",0.446468,1.000000,1.000000
28,"{'max_depth': 14, 'n_estimators': 200}",0.857304,1.000000,1.000000
29,"{'max_depth': 14, 'n_estimators': 300}",1.951553,1.000000,1.000000

In [157]:
grid_search_RF.best_params_  # Print best hyperparameters for the model

{'max_depth': 8, 'n_estimators': 100}

In [158]:
# Random Forest Classifier:
random_forest_cls_tuned = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=13)
random_forest_cls_tuned.fit(X_train, y_train)

# Find test accuracy for all models:
print("Test Score for Random Forest: ", random_forest_cls_tuned.score(X_test, y_test))

Test Score for Random Forest:  1.0